### PR TITLE
Updated pokemon.json

### PR DESCRIPTION
**Pull request by sysopmatt**
@frontsideair I updated the pokemon.json file.  I believe that's really the only fields you're using.

### CODE REVIEW

**Comment by frontsideair** [comment]
Thanks for updating the list, but I tried with your commit and it seems to show wrong pokemon when `-d` parameter is used. That's probably because the pokemon list is not sorted, can you send another commit and sort it?

I used other info in the json for displaying but I don't use it that much so it's no big loss. Maintaining the list would probably be harder.

By the way, why is there a `show_filter` property and why only Zubat doesn't have it?

**Comment by frontsideair** [comment]
The script was no longer working and I had some time so I rewrote and simplified it. I also merged your commit and generated friendlier messages. Thanks for the PR and you're welcome to contribute more.

**Comment by sysopmatt** [comment]
Great! Working on percentages tonight. I'll try and make a PR for it tomorrow! I already have it working from my previous work, just need to clean it up a bit!

EDIT: I made a PR for this.

**Comment by sysopmatt** [comment]
@frontsideair I also wanted to mention that you may want to update the readme; the pokemon.json list I made a PR request was posted on Reddit, and actually came from: https://github.com/SebastianBar/iv-nickname/

**Comment by frontsideair** [comment]
Thanks for informing me, I'll update this.

**Pull request merged**
